local opt = vim.opt
opt.number = true
opt.relativenumber = true
opt.termguicolors = true
opt.cursorline = true
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.swapfile = false
opt.backup = false
opt.undofile = true
opt.clipboard = "unnamedplus"
opt.mouse = "a"
