#!/usr/bin/env bash

# Kill existing instances
killall -q polybar

# Wait until processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar (replace 'main' with your bar name from config)
polybar &

